SEASONS = ["Spring", "Summer", "Autumn", "Winter"]

BUILDINGS = {
    "farm": {
        "name": "Farm",
        "cost": {"gold": 50, "wood": 30, "stone": 0},
        "upkeep": 0,
        "production": {"food": 20},
        "description": "Produces food for your people.",
    },
    "lumber_mill": {
        "name": "Lumber Mill",
        "cost": {"gold": 40, "wood": 20, "stone": 0},
        "upkeep": 1,
        "production": {"wood": 15},
        "description": "Harvests wood from nearby forests.",
    },
    "quarry": {
        "name": "Quarry",
        "cost": {"gold": 60, "wood": 20, "stone": 10},
        "upkeep": 2,
        "production": {"stone": 12},
        "description": "Mines stone from the hills.",
    },
    "market": {
        "name": "Market",
        "cost": {"gold": 80, "wood": 30, "stone": 20},
        "upkeep": 0,
        "production": {"gold": 25},
        "description": "Brings merchants and gold to your kingdom.",
    },
    "barracks": {
        "name": "Barracks",
        "cost": {"gold": 100, "wood": 40, "stone": 30},
        "upkeep": 5,
        "production": {},
        "description": "Allows you to recruit up to 20 soldiers.",
        "soldier_capacity": 20,
    },
    "walls": {
        "name": "Stone Walls",
        "cost": {"gold": 20, "wood": 20, "stone": 80},
        "upkeep": 0,
        "production": {},
        "description": "Fortifies your settlement (+25 defense).",
        "defense_bonus": 25,
    },
    "tavern": {
        "name": "Tavern",
        "cost": {"gold": 60, "wood": 30, "stone": 10},
        "upkeep": 2,
        "production": {"gold": 8},
        "description": "Raises morale and attracts travelers.",
        "morale_per_turn": 5,
    },
    "blacksmith": {
        "name": "Blacksmith",
        "cost": {"gold": 80, "wood": 20, "stone": 30},
        "upkeep": 5,
        "production": {},
        "description": "Forges weapons to boost your soldiers (+10 attack).",
        "attack_bonus": 10,
    },
    "castle": {
        "name": "Castle",
        "cost": {"gold": 300, "wood": 60, "stone": 120},
        "upkeep": 10,
        "production": {},
        "description": "A symbol of royal power (+5 prestige/turn, +30 defense).",
        "prestige_per_turn": 5,
        "defense_bonus": 30,
    },
    "cathedral": {
        "name": "Cathedral",
        "cost": {"gold": 200, "wood": 50, "stone": 80},
        "upkeep": 5,
        "production": {},
        "description": "A place of worship (+15 morale/turn, +3 prestige/turn). Requires Castle.",
        "requires": "castle",
        "morale_per_turn": 15,
        "prestige_per_turn": 3,
    },
}

EVENTS = [
    {
        "id": "good_harvest",
        "name": "Bountiful Harvest",
        "message": "The fields yield an exceptional harvest! (+50 food)",
        "food": 50,
        "weight": 10,
    },
    {
        "id": "merchant",
        "name": "Traveling Merchant",
        "message": "A rich merchant pays tribute to your kingdom. (+35 gold)",
        "gold": 35,
        "weight": 8,
    },
    {
        "id": "plague",
        "name": "Plague Outbreak",
        "message": "A plague sweeps through your kingdom! (-15 population, -15 morale)",
        "population": -15,
        "morale": -15,
        "weight": 3,
    },
    {
        "id": "bandit_raid",
        "name": "Bandit Raid",
        "message": "Bandits are spotted approaching your kingdom!",
        "weight": 6,
        "defended_message": "Your soldiers repelled the attack! (+5 prestige)",
        "defended": {"prestige": 5},
        "undefended_message": "No defenders! Resources were plundered. (-60 gold, -30 food)",
        "undefended": {"gold": -60, "food": -30},
    },
    {
        "id": "fire",
        "name": "Great Fire",
        "message": "Fire breaks out in the settlement! (-30 wood, -10 morale)",
        "wood": -30,
        "morale": -10,
        "weight": 4,
    },
    {
        "id": "festival",
        "name": "Harvest Festival",
        "message": "The people celebrate a grand festival! (+20 morale, -15 gold)",
        "morale": 20,
        "gold": -15,
        "weight": 7,
    },
    {
        "id": "noble_visit",
        "name": "Foreign Noble Visit",
        "message": "A foreign noble visits and is impressed by your realm. (+10 prestige, +30 gold)",
        "prestige": 10,
        "gold": 30,
        "weight": 5,
    },
    {
        "id": "drought",
        "name": "Drought",
        "message": "A drought withers the crops. (-30 food)",
        "food": -30,
        "weight": 5,
    },
    {
        "id": "settlers",
        "name": "Settlers Arrive",
        "message": "A group of settlers seeks refuge in your kingdom. (+12 population)",
        "population": 12,
        "weight": 7,
    },
    {
        "id": "discovery",
        "name": "Stone Discovery",
        "message": "Miners discover a rich stone deposit! (+40 stone)",
        "stone": 40,
        "weight": 6,
    },
]

WIN_PRESTIGE = 100
STARTING_RESOURCES = {"gold": 200, "food": 150, "wood": 80, "stone": 30}
STARTING_POPULATION = 40
